# Generated by Django 3.2.8 on 2024-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestalk',
            name='title',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='standard',
            name='comment',
            field=models.TextField(default='default comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='template',
            field=models.CharField(default='default sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='comment',
            field=models.TextField(verbose_name='ひとことコメント'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='day',
            field=models.CharField(max_length=5, verbose_name='開催日（『4/1』の形式で半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='guest',
            field=models.CharField(max_length=50, verbose_name='ゲスト名'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='guest_url',
            field=models.CharField(max_length=200, verbose_name='ゲストプロフィールURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='spreadsheet',
            field=models.CharField(max_length=150, verbose_name='質問スプシURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='template',
            field=models.CharField(max_length=50, verbose_name='自己紹介テンプレ⑤'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='theme',
            field=models.CharField(max_length=50, verbose_name='お題（『〇〇について聞いてみよう』の〇〇のみ入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='thumbnail',
            field=models.CharField(max_length=150, verbose_name='サムネURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='vol',
            field=models.CharField(max_length=2, verbose_name='開催回（『vol.〇』の〇のみ半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='zoom',
            field=models.CharField(max_length=100, verbose_name='zoomリンク'),
        ),
    ]
