# Generated by Django 3.2.8 on 2024-09-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular', '0002_auto_20240806_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestalk',
            name='day',
            field=models.DateField(verbose_name='開催日（『4/1』の形式で半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='guest_url',
            field=models.URLField(verbose_name='ゲストプロフィールURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='spreadsheet',
            field=models.URLField(verbose_name='質問スプシURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='thumbnail',
            field=models.URLField(verbose_name='サムネURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='vol',
            field=models.PositiveIntegerField(verbose_name='開催回（『vol.〇』の〇のみ半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='zoom',
            field=models.URLField(verbose_name='zoomリンク'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='zoom',
            field=models.URLField(),
        ),
    ]
