# Generated by Django 3.2.8 on 2024-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular', '0002_auto_20240806_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='template',
        ),
        migrations.AddField(
            model_name='standard',
            name='comment1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='comment2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='comment3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='comment4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='comment5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='template1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='standard',
            name='template2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='standard',
            name='template3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='standard',
            name='template4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='standard',
            name='template5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='day',
            field=models.DateField(verbose_name='開催日（『4/1』の形式で半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='guest_url',
            field=models.URLField(verbose_name='ゲストプロフィールURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='spreadsheet',
            field=models.URLField(verbose_name='質問スプシURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='thumbnail',
            field=models.URLField(verbose_name='サムネURL'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='vol',
            field=models.PositiveIntegerField(verbose_name='開催回（『vol.〇』の〇のみ半角入力）'),
        ),
        migrations.AlterField(
            model_name='guestalk',
            name='zoom',
            field=models.URLField(verbose_name='zoomリンク'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='zoom',
            field=models.URLField(),
        ),
    ]
